-- labs/campus — 10 entities. Applied to D1 oat-labs-campus.
CREATE TABLE IF NOT EXISTS idempotency (key TEXT PRIMARY KEY, record TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS invites (grant_id TEXT PRIMARY KEY, token TEXT NOT NULL UNIQUE, entity TEXT NOT NULL, item_id TEXT NOT NULL, owner_org TEXT NOT NULL, grantee_key TEXT NOT NULL, accepted INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS "campuses" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "building_count" INTEGER, "ticket_count" INTEGER, "course_count" INTEGER, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "campuses_org" ON "campuses" (org_id, id);
CREATE TABLE IF NOT EXISTS "buildings" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "campus_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "room_count" INTEGER, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "buildings_org" ON "buildings" (org_id, id);
CREATE TABLE IF NOT EXISTS "rooms" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "building_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "booking_count" INTEGER, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "rooms_org" ON "rooms" (org_id, id);
CREATE TABLE IF NOT EXISTS "staff" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "staff_org" ON "staff" (org_id, id);
CREATE TABLE IF NOT EXISTS "bookings" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "room_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "bookings_org" ON "bookings" (org_id, id);
CREATE TABLE IF NOT EXISTS "tickets" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "campus_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER, "deleted_at" INTEGER);
CREATE INDEX IF NOT EXISTS "tickets_org" ON "tickets" (org_id, deleted_at, id);
CREATE TABLE IF NOT EXISTS "equipment" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "building_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "equipment_org" ON "equipment" (org_id, id);
CREATE TABLE IF NOT EXISTS "announcements" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "campus_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "announcements_org" ON "announcements" (org_id, id);
CREATE TABLE IF NOT EXISTS "courses" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "campus_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "enrollment_count" INTEGER, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "courses_org" ON "courses" (org_id, id);
CREATE TABLE IF NOT EXISTS "enrollments" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "course_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "enrollments_org" ON "enrollments" (org_id, id);
