-- labs/huge — 200 entities. Applied to D1 oat-labs-huge.
CREATE TABLE IF NOT EXISTS idempotency (key TEXT PRIMARY KEY, record TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS invites (grant_id TEXT PRIMARY KEY, token TEXT NOT NULL UNIQUE, entity TEXT NOT NULL, item_id TEXT NOT NULL, owner_org TEXT NOT NULL, grantee_key TEXT NOT NULL, accepted INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS "r00s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "r00c0_count" INTEGER, "r00c1_count" INTEGER, "r00c2_count" INTEGER, "r00c3_count" INTEGER, "r00c4_count" INTEGER, "r00c5_count" INTEGER, "r00c6_count" INTEGER, "r00c7_count" INTEGER, "r00c8_count" INTEGER, "created_at" INTEGER, "updated_at" INTEGER, "deleted_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r00s_org" ON "r00s" (org_id, deleted_at, id);
CREATE TABLE IF NOT EXISTS "r00c0s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r00_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r00c0s_org" ON "r00c0s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r00c1s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r00_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r00c1s_org" ON "r00c1s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r00c2s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r00_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r00c2s_org" ON "r00c2s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r00c3s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r00_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r00c3s_org" ON "r00c3s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r00c4s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r00_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r00c4s_org" ON "r00c4s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r00c5s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r00_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r00c5s_org" ON "r00c5s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r00c6s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r00_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r00c6s_org" ON "r00c6s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r00c7s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r00_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r00c7s_org" ON "r00c7s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r00c8s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r00_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r00c8s_org" ON "r00c8s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r01s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "r01c0_count" INTEGER, "r01c1_count" INTEGER, "r01c2_count" INTEGER, "r01c3_count" INTEGER, "r01c4_count" INTEGER, "r01c5_count" INTEGER, "r01c6_count" INTEGER, "r01c7_count" INTEGER, "r01c8_count" INTEGER, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r01s_org" ON "r01s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r01c0s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r01_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r01c0s_org" ON "r01c0s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r01c1s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r01_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r01c1s_org" ON "r01c1s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r01c2s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r01_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r01c2s_org" ON "r01c2s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r01c3s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r01_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r01c3s_org" ON "r01c3s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r01c4s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r01_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r01c4s_org" ON "r01c4s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r01c5s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r01_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r01c5s_org" ON "r01c5s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r01c6s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r01_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r01c6s_org" ON "r01c6s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r01c7s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r01_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r01c7s_org" ON "r01c7s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r01c8s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r01_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r01c8s_org" ON "r01c8s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r02s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "r02c0_count" INTEGER, "r02c1_count" INTEGER, "r02c2_count" INTEGER, "r02c3_count" INTEGER, "r02c4_count" INTEGER, "r02c5_count" INTEGER, "r02c6_count" INTEGER, "r02c7_count" INTEGER, "r02c8_count" INTEGER, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r02s_org" ON "r02s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r02c0s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r02_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r02c0s_org" ON "r02c0s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r02c1s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r02_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r02c1s_org" ON "r02c1s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r02c2s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r02_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r02c2s_org" ON "r02c2s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r02c3s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r02_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r02c3s_org" ON "r02c3s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r02c4s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r02_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r02c4s_org" ON "r02c4s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r02c5s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r02_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r02c5s_org" ON "r02c5s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r02c6s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r02_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r02c6s_org" ON "r02c6s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r02c7s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r02_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r02c7s_org" ON "r02c7s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r02c8s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r02_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r02c8s_org" ON "r02c8s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r03s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "r03c0_count" INTEGER, "r03c1_count" INTEGER, "r03c2_count" INTEGER, "r03c3_count" INTEGER, "r03c4_count" INTEGER, "r03c5_count" INTEGER, "r03c6_count" INTEGER, "r03c7_count" INTEGER, "r03c8_count" INTEGER, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r03s_org" ON "r03s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r03c0s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r03_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r03c0s_org" ON "r03c0s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r03c1s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r03_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r03c1s_org" ON "r03c1s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r03c2s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r03_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r03c2s_org" ON "r03c2s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r03c3s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r03_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r03c3s_org" ON "r03c3s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r03c4s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r03_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r03c4s_org" ON "r03c4s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r03c5s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r03_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r03c5s_org" ON "r03c5s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r03c6s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r03_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r03c6s_org" ON "r03c6s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r03c7s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r03_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r03c7s_org" ON "r03c7s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r03c8s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r03_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r03c8s_org" ON "r03c8s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r04s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "r04c0_count" INTEGER, "r04c1_count" INTEGER, "r04c2_count" INTEGER, "r04c3_count" INTEGER, "r04c4_count" INTEGER, "r04c5_count" INTEGER, "r04c6_count" INTEGER, "r04c7_count" INTEGER, "r04c8_count" INTEGER, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r04s_org" ON "r04s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r04c0s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r04_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r04c0s_org" ON "r04c0s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r04c1s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r04_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r04c1s_org" ON "r04c1s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r04c2s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r04_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r04c2s_org" ON "r04c2s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r04c3s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r04_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r04c3s_org" ON "r04c3s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r04c4s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r04_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r04c4s_org" ON "r04c4s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r04c5s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r04_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r04c5s_org" ON "r04c5s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r04c6s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r04_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r04c6s_org" ON "r04c6s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r04c7s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r04_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r04c7s_org" ON "r04c7s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r04c8s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r04_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r04c8s_org" ON "r04c8s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r05s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "r05c0_count" INTEGER, "r05c1_count" INTEGER, "r05c2_count" INTEGER, "r05c3_count" INTEGER, "r05c4_count" INTEGER, "r05c5_count" INTEGER, "r05c6_count" INTEGER, "r05c7_count" INTEGER, "r05c8_count" INTEGER, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r05s_org" ON "r05s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r05c0s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r05_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r05c0s_org" ON "r05c0s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r05c1s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r05_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r05c1s_org" ON "r05c1s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r05c2s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r05_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r05c2s_org" ON "r05c2s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r05c3s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r05_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r05c3s_org" ON "r05c3s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r05c4s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r05_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r05c4s_org" ON "r05c4s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r05c5s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r05_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r05c5s_org" ON "r05c5s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r05c6s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r05_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r05c6s_org" ON "r05c6s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r05c7s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r05_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r05c7s_org" ON "r05c7s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r05c8s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r05_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r05c8s_org" ON "r05c8s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r06s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "r06c0_count" INTEGER, "r06c1_count" INTEGER, "r06c2_count" INTEGER, "r06c3_count" INTEGER, "r06c4_count" INTEGER, "r06c5_count" INTEGER, "r06c6_count" INTEGER, "r06c7_count" INTEGER, "r06c8_count" INTEGER, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r06s_org" ON "r06s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r06c0s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r06_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r06c0s_org" ON "r06c0s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r06c1s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r06_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r06c1s_org" ON "r06c1s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r06c2s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r06_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r06c2s_org" ON "r06c2s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r06c3s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r06_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r06c3s_org" ON "r06c3s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r06c4s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r06_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r06c4s_org" ON "r06c4s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r06c5s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r06_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r06c5s_org" ON "r06c5s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r06c6s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r06_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r06c6s_org" ON "r06c6s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r06c7s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r06_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r06c7s_org" ON "r06c7s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r06c8s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r06_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r06c8s_org" ON "r06c8s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r07s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "r07c0_count" INTEGER, "r07c1_count" INTEGER, "r07c2_count" INTEGER, "r07c3_count" INTEGER, "r07c4_count" INTEGER, "r07c5_count" INTEGER, "r07c6_count" INTEGER, "r07c7_count" INTEGER, "r07c8_count" INTEGER, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r07s_org" ON "r07s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r07c0s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r07_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r07c0s_org" ON "r07c0s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r07c1s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r07_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r07c1s_org" ON "r07c1s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r07c2s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r07_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r07c2s_org" ON "r07c2s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r07c3s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r07_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r07c3s_org" ON "r07c3s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r07c4s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r07_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r07c4s_org" ON "r07c4s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r07c5s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r07_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r07c5s_org" ON "r07c5s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r07c6s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r07_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r07c6s_org" ON "r07c6s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r07c7s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r07_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r07c7s_org" ON "r07c7s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r07c8s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r07_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r07c8s_org" ON "r07c8s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r08s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "r08c0_count" INTEGER, "r08c1_count" INTEGER, "r08c2_count" INTEGER, "r08c3_count" INTEGER, "r08c4_count" INTEGER, "r08c5_count" INTEGER, "r08c6_count" INTEGER, "r08c7_count" INTEGER, "r08c8_count" INTEGER, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r08s_org" ON "r08s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r08c0s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r08_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r08c0s_org" ON "r08c0s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r08c1s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r08_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r08c1s_org" ON "r08c1s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r08c2s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r08_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r08c2s_org" ON "r08c2s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r08c3s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r08_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r08c3s_org" ON "r08c3s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r08c4s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r08_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r08c4s_org" ON "r08c4s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r08c5s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r08_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r08c5s_org" ON "r08c5s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r08c6s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r08_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r08c6s_org" ON "r08c6s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r08c7s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r08_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r08c7s_org" ON "r08c7s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r08c8s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r08_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r08c8s_org" ON "r08c8s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r09s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "r09c0_count" INTEGER, "r09c1_count" INTEGER, "r09c2_count" INTEGER, "r09c3_count" INTEGER, "r09c4_count" INTEGER, "r09c5_count" INTEGER, "r09c6_count" INTEGER, "r09c7_count" INTEGER, "r09c8_count" INTEGER, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r09s_org" ON "r09s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r09c0s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r09_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r09c0s_org" ON "r09c0s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r09c1s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r09_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r09c1s_org" ON "r09c1s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r09c2s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r09_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r09c2s_org" ON "r09c2s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r09c3s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r09_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r09c3s_org" ON "r09c3s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r09c4s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r09_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r09c4s_org" ON "r09c4s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r09c5s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r09_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r09c5s_org" ON "r09c5s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r09c6s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r09_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r09c6s_org" ON "r09c6s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r09c7s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r09_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r09c7s_org" ON "r09c7s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r09c8s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r09_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r09c8s_org" ON "r09c8s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r10s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "r10c0_count" INTEGER, "r10c1_count" INTEGER, "r10c2_count" INTEGER, "r10c3_count" INTEGER, "r10c4_count" INTEGER, "r10c5_count" INTEGER, "r10c6_count" INTEGER, "r10c7_count" INTEGER, "r10c8_count" INTEGER, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r10s_org" ON "r10s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r10c0s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r10_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r10c0s_org" ON "r10c0s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r10c1s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r10_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r10c1s_org" ON "r10c1s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r10c2s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r10_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r10c2s_org" ON "r10c2s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r10c3s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r10_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r10c3s_org" ON "r10c3s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r10c4s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r10_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r10c4s_org" ON "r10c4s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r10c5s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r10_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r10c5s_org" ON "r10c5s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r10c6s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r10_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r10c6s_org" ON "r10c6s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r10c7s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r10_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r10c7s_org" ON "r10c7s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r10c8s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r10_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r10c8s_org" ON "r10c8s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r11s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "r11c0_count" INTEGER, "r11c1_count" INTEGER, "r11c2_count" INTEGER, "r11c3_count" INTEGER, "r11c4_count" INTEGER, "r11c5_count" INTEGER, "r11c6_count" INTEGER, "r11c7_count" INTEGER, "r11c8_count" INTEGER, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r11s_org" ON "r11s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r11c0s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r11_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r11c0s_org" ON "r11c0s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r11c1s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r11_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r11c1s_org" ON "r11c1s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r11c2s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r11_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r11c2s_org" ON "r11c2s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r11c3s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r11_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r11c3s_org" ON "r11c3s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r11c4s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r11_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r11c4s_org" ON "r11c4s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r11c5s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r11_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r11c5s_org" ON "r11c5s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r11c6s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r11_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r11c6s_org" ON "r11c6s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r11c7s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r11_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r11c7s_org" ON "r11c7s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r11c8s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r11_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r11c8s_org" ON "r11c8s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r12s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "r12c0_count" INTEGER, "r12c1_count" INTEGER, "r12c2_count" INTEGER, "r12c3_count" INTEGER, "r12c4_count" INTEGER, "r12c5_count" INTEGER, "r12c6_count" INTEGER, "r12c7_count" INTEGER, "r12c8_count" INTEGER, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r12s_org" ON "r12s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r12c0s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r12_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r12c0s_org" ON "r12c0s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r12c1s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r12_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r12c1s_org" ON "r12c1s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r12c2s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r12_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r12c2s_org" ON "r12c2s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r12c3s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r12_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r12c3s_org" ON "r12c3s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r12c4s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r12_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r12c4s_org" ON "r12c4s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r12c5s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r12_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r12c5s_org" ON "r12c5s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r12c6s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r12_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r12c6s_org" ON "r12c6s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r12c7s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r12_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r12c7s_org" ON "r12c7s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r12c8s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r12_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r12c8s_org" ON "r12c8s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r13s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "r13c0_count" INTEGER, "r13c1_count" INTEGER, "r13c2_count" INTEGER, "r13c3_count" INTEGER, "r13c4_count" INTEGER, "r13c5_count" INTEGER, "r13c6_count" INTEGER, "r13c7_count" INTEGER, "r13c8_count" INTEGER, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r13s_org" ON "r13s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r13c0s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r13_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r13c0s_org" ON "r13c0s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r13c1s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r13_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r13c1s_org" ON "r13c1s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r13c2s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r13_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r13c2s_org" ON "r13c2s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r13c3s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r13_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r13c3s_org" ON "r13c3s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r13c4s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r13_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r13c4s_org" ON "r13c4s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r13c5s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r13_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r13c5s_org" ON "r13c5s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r13c6s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r13_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r13c6s_org" ON "r13c6s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r13c7s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r13_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r13c7s_org" ON "r13c7s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r13c8s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r13_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r13c8s_org" ON "r13c8s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r14s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "r14c0_count" INTEGER, "r14c1_count" INTEGER, "r14c2_count" INTEGER, "r14c3_count" INTEGER, "r14c4_count" INTEGER, "r14c5_count" INTEGER, "r14c6_count" INTEGER, "r14c7_count" INTEGER, "r14c8_count" INTEGER, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r14s_org" ON "r14s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r14c0s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r14_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r14c0s_org" ON "r14c0s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r14c1s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r14_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r14c1s_org" ON "r14c1s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r14c2s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r14_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r14c2s_org" ON "r14c2s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r14c3s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r14_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r14c3s_org" ON "r14c3s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r14c4s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r14_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r14c4s_org" ON "r14c4s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r14c5s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r14_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r14c5s_org" ON "r14c5s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r14c6s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r14_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r14c6s_org" ON "r14c6s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r14c7s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r14_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r14c7s_org" ON "r14c7s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r14c8s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r14_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r14c8s_org" ON "r14c8s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r15s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "r15c0_count" INTEGER, "r15c1_count" INTEGER, "r15c2_count" INTEGER, "r15c3_count" INTEGER, "r15c4_count" INTEGER, "r15c5_count" INTEGER, "r15c6_count" INTEGER, "r15c7_count" INTEGER, "r15c8_count" INTEGER, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r15s_org" ON "r15s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r15c0s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r15_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r15c0s_org" ON "r15c0s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r15c1s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r15_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r15c1s_org" ON "r15c1s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r15c2s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r15_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r15c2s_org" ON "r15c2s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r15c3s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r15_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r15c3s_org" ON "r15c3s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r15c4s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r15_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r15c4s_org" ON "r15c4s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r15c5s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r15_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r15c5s_org" ON "r15c5s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r15c6s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r15_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r15c6s_org" ON "r15c6s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r15c7s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r15_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r15c7s_org" ON "r15c7s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r15c8s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r15_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r15c8s_org" ON "r15c8s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r16s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "r16c0_count" INTEGER, "r16c1_count" INTEGER, "r16c2_count" INTEGER, "r16c3_count" INTEGER, "r16c4_count" INTEGER, "r16c5_count" INTEGER, "r16c6_count" INTEGER, "r16c7_count" INTEGER, "r16c8_count" INTEGER, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r16s_org" ON "r16s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r16c0s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r16_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r16c0s_org" ON "r16c0s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r16c1s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r16_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r16c1s_org" ON "r16c1s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r16c2s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r16_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r16c2s_org" ON "r16c2s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r16c3s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r16_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r16c3s_org" ON "r16c3s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r16c4s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r16_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r16c4s_org" ON "r16c4s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r16c5s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r16_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r16c5s_org" ON "r16c5s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r16c6s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r16_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r16c6s_org" ON "r16c6s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r16c7s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r16_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r16c7s_org" ON "r16c7s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r16c8s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r16_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r16c8s_org" ON "r16c8s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r17s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "r17c0_count" INTEGER, "r17c1_count" INTEGER, "r17c2_count" INTEGER, "r17c3_count" INTEGER, "r17c4_count" INTEGER, "r17c5_count" INTEGER, "r17c6_count" INTEGER, "r17c7_count" INTEGER, "r17c8_count" INTEGER, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r17s_org" ON "r17s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r17c0s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r17_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r17c0s_org" ON "r17c0s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r17c1s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r17_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r17c1s_org" ON "r17c1s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r17c2s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r17_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r17c2s_org" ON "r17c2s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r17c3s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r17_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r17c3s_org" ON "r17c3s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r17c4s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r17_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r17c4s_org" ON "r17c4s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r17c5s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r17_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r17c5s_org" ON "r17c5s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r17c6s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r17_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r17c6s_org" ON "r17c6s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r17c7s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r17_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r17c7s_org" ON "r17c7s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r17c8s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r17_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r17c8s_org" ON "r17c8s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r18s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "r18c0_count" INTEGER, "r18c1_count" INTEGER, "r18c2_count" INTEGER, "r18c3_count" INTEGER, "r18c4_count" INTEGER, "r18c5_count" INTEGER, "r18c6_count" INTEGER, "r18c7_count" INTEGER, "r18c8_count" INTEGER, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r18s_org" ON "r18s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r18c0s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r18_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r18c0s_org" ON "r18c0s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r18c1s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r18_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r18c1s_org" ON "r18c1s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r18c2s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r18_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r18c2s_org" ON "r18c2s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r18c3s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r18_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r18c3s_org" ON "r18c3s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r18c4s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r18_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r18c4s_org" ON "r18c4s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r18c5s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r18_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r18c5s_org" ON "r18c5s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r18c6s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r18_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r18c6s_org" ON "r18c6s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r18c7s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r18_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r18c7s_org" ON "r18c7s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r18c8s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r18_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r18c8s_org" ON "r18c8s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r19s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "r19c0_count" INTEGER, "r19c1_count" INTEGER, "r19c2_count" INTEGER, "r19c3_count" INTEGER, "r19c4_count" INTEGER, "r19c5_count" INTEGER, "r19c6_count" INTEGER, "r19c7_count" INTEGER, "r19c8_count" INTEGER, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r19s_org" ON "r19s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r19c0s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r19_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r19c0s_org" ON "r19c0s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r19c1s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r19_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r19c1s_org" ON "r19c1s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r19c2s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r19_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r19c2s_org" ON "r19c2s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r19c3s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r19_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r19c3s_org" ON "r19c3s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r19c4s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r19_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r19c4s_org" ON "r19c4s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r19c5s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r19_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r19c5s_org" ON "r19c5s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r19c6s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r19_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r19c6s_org" ON "r19c6s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r19c7s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r19_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r19c7s_org" ON "r19c7s" (org_id, id);
CREATE TABLE IF NOT EXISTS "r19c8s" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "r19_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "r19c8s_org" ON "r19c8s" (org_id, id);
