-- labs/platform — 20 entities. Applied to D1 oat-labs-platform.
CREATE TABLE IF NOT EXISTS idempotency (key TEXT PRIMARY KEY, record TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS invites (grant_id TEXT PRIMARY KEY, token TEXT NOT NULL UNIQUE, entity TEXT NOT NULL, item_id TEXT NOT NULL, owner_org TEXT NOT NULL, grantee_key TEXT NOT NULL, accepted INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS "workspaces" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "project_count" INTEGER, "webhook_count" INTEGER, "member_count" INTEGER, "created_at" INTEGER, "updated_at" INTEGER, "deleted_at" INTEGER);
CREATE INDEX IF NOT EXISTS "workspaces_org" ON "workspaces" (org_id, deleted_at, id);
CREATE TABLE IF NOT EXISTS "projects" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "workspace_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "board_count" INTEGER, "issue_count" INTEGER, "doc_count" INTEGER, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "projects_org" ON "projects" (org_id, id);
CREATE TABLE IF NOT EXISTS "boards" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "project_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "card_count" INTEGER, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "boards_org" ON "boards" (org_id, id);
CREATE TABLE IF NOT EXISTS "cards" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "board_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "comment_count" INTEGER, "attachment_count" INTEGER, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "cards_org" ON "cards" (org_id, id);
CREATE TABLE IF NOT EXISTS "comments" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "card_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "comments_org" ON "comments" (org_id, id);
CREATE TABLE IF NOT EXISTS "labels" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "project_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "labels_org" ON "labels" (org_id, id);
CREATE TABLE IF NOT EXISTS "attachments" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "card_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "attachments_org" ON "attachments" (org_id, id);
CREATE TABLE IF NOT EXISTS "webhooks" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "workspace_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "webhooks_org" ON "webhooks" (org_id, id);
CREATE TABLE IF NOT EXISTS "members" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "workspace_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "members_org" ON "members" (org_id, id);
CREATE TABLE IF NOT EXISTS "sprints" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "project_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "sprints_org" ON "sprints" (org_id, id);
CREATE TABLE IF NOT EXISTS "issues" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "project_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "review_count" INTEGER, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "issues_org" ON "issues" (org_id, id);
CREATE TABLE IF NOT EXISTS "docs" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "project_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "docs_org" ON "docs" (org_id, id);
CREATE TABLE IF NOT EXISTS "reviews" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "issue_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "reviews_org" ON "reviews" (org_id, id);
CREATE TABLE IF NOT EXISTS "environments" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "project_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "deployment_count" INTEGER, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "environments_org" ON "environments" (org_id, id);
CREATE TABLE IF NOT EXISTS "deployments" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "environment_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "deployments_org" ON "deployments" (org_id, id);
CREATE TABLE IF NOT EXISTS "flags" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "project_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "flags_org" ON "flags" (org_id, id);
CREATE TABLE IF NOT EXISTS "secrets" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "environment_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "secrets_org" ON "secrets" (org_id, id);
CREATE TABLE IF NOT EXISTS "metrics" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "project_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "metrics_org" ON "metrics" (org_id, id);
CREATE TABLE IF NOT EXISTS "audits" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "workspace_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "audits_org" ON "audits" (org_id, id);
CREATE TABLE IF NOT EXISTS "inboxes" ("id" TEXT PRIMARY KEY, "org_id" TEXT NOT NULL, "workspace_id" TEXT, "name" TEXT, "status" TEXT, "position" INTEGER, "note" TEXT, "kind" TEXT, "created_at" INTEGER, "updated_at" INTEGER);
CREATE INDEX IF NOT EXISTS "inboxes_org" ON "inboxes" (org_id, id);
